Repository vovakorolikhin/MoneySaver, pull requests merged in 2019-10, with the labels that each got.

#13 Prototype
  Code/MoneySaver/app/src/main/java/com/moneysaver/Config.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/CreditPackage/CreditView.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/ExpensePackage/AddExpense.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/ExpensePackage/DeleteExpense.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/ExpensePackage/ExpenseView.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/GoalPackge/GoalView.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/GoalPackge/ListGoal.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/MainActivity.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/SQLite.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/SaveMoney.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/Settings/AddCategories.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/Settings/Settings.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/Settings/SettingsAdapter.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/Settings/VariableFields.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/Statistics/Statistics.java
Labels: bug, optimization

#17 design
  Code/MoneySaver/app/src/main/AndroidManifest.xml
  Code/MoneySaver/app/src/main/java/com/moneysaver/CreditPackage/DeleteCredit.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/CreditPackage/EditCredit.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/ExpensePackage/AdapterExpense.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/ExpensePackage/EditExpense.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/ExpensePackage/ListExpense.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/GoalPackge/DeleteGoal.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/GoalPackge/EditGoal.java
  Code/MoneySaver/app/src/main/res/layout/add_categories.xml
  Code/MoneySaver/app/src/main/res/layout/add_categories_adapter.xml
  Code/MoneySaver/app/src/main/res/layout/add_credit.xml
  Code/MoneySaver/app/src/main/res/layout/add_goal.xml
  Code/MoneySaver/app/src/main/res/layout/edit_credit.xml
  Code/MoneySaver/app/src/main/res/layout/edit_expense.xml
  Code/MoneySaver/app/src/main/res/layout/edit_goal.xml
  Code/MoneySaver/app/src/main/res/layout/list_item_expense.xml
  Code/MoneySaver/app/src/main/res/layout/save_money.xml
Labels: bug, optimization, refactoring

#16 Add Bugs, UML, autocomplete categories, double numbers to EditText
  Bugs/Detected bugs.txt
  Code/MoneySaver/app/src/main/java/com/moneysaver/Config.java
  Code/MoneySaver/app/src/main/java/com/moneysaver/MainActivity.java
  Code/MoneySaver/app/src/main/res/layout/add_categories_adapter.xml
  Code/MoneySaver/app/src/main/res/layout/add_expense.xml
  Code/MoneySaver/app/src/main/res/layout/dialog_category.xml
  Code/MoneySaver/app/src/main/res/layout/settings.xml
  UML/UML.png
Labels: bug, documentation, feature
